spring.application.name=paperreview
spring.datasource.url=jdbc:mysql://localhost:3306/paper_system
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082